### ISSUE TITLE
Error : Inference on pre-trained model

### ISSUE THREAD

**Issue by bharat-patidar** [lettergram/sentence-classification#3]
Hi,
I was trying to test on pre-trained model(cnn). I successfully loaded your model with following commands :
 ```
   # load json and create model
    json_file = open(model_name + '.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    model = model_from_json(loaded_model_json)
```

Now, when I tried to test it through following code:
```

test_comments, test_comments_category = get_custom_test_comments()

x_test, _, y_test, _ = encode_data(test_comments, test_comments_category,
                                   data_split=1.0,
                                   embedding_name=embedding_name,
                                   add_pos_tags_flag=pos_tags_flag)

x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
y_test = keras.utils.to_categorical(y_test, num_classes)

score = model.evaluate(x_test, y_test,
                       batch_size=batch_size, verbose=1)
```

^this last line of model.evaluate resulted in error : 
```

InvalidArgumentError: indices[13,490] = 22271 is not in [0, 15000)
	 [[Node: embedding_1_9/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@dropout_1_9/cond/Switch_1"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1_9/embeddings/read, embedding_1_9/Cast, embedding_1_9/embedding_lookup/axis)]]

```
which I figured out that it might be because of word id which is contained in x_test, because value of max_words which we have is 15000 and maximum value in x_test is far greater than 15000 so it's not able to find words which have id greater than 15000. I tried to divide all the values of x_test by 100 and then converted all the values to integer. Then it successfully worked.

So , can you please suggest me If I  am doing anything wrong, or any other word encoding needs to be loaded?
Thanks for the help.

**Comment by lettergram** [comment]
Hello!

A few questions, as I'm trying to replicate the issue.

1. It works out of the box on multiple devices if I run `python3 sentence_cnn_model_saving.py`, is that what you are doing?

2. Are you training a custom model?

**Comment by bharat-patidar** [comment]
Hi Austin,
Yes, I am using sentence_cnn_model_saving.py script and extracted few lines of code(mentioned above) which loads the model but when I try to test it on your sample dataset it throws the error. I am not building any custom model. I am just trying to test your pretrained model.

**Comment by lettergram** [comment]
@bharat-patidar I am using python 3.7, Keras 2.2.4, CUDA 10 and TF 1.13.1 and ran the following successfully:

```
$ python3 sentence_cnn_model_saving.py models/cnn
Using TensorFlow backend.
models/cnn
Load Model? False
Loading Data...
170004 train sequences
42502 test sequences
3 classes
Pad sequences (samples x time)
Convert class vector to binary class matrix (for use with categorical_crossentropy)
Loading model!

42502/42502 [==============================] - 3s 59us/step
Test accuracy: 0.9729424497670698

Creating Manual Test...
Encoding Data...
Embedding Name data/default
[1 1 1 0 2 1 2 2 0 0 0 2 1 2 0]
15 train sequences
0 test sequences
15/15 [==============================] - 0s 179us/step
Manual test
Test accuracy: 0.9333333373069763
15
15/15 [==============================] - 0s 2ms/step
Predictions
Real [1, 1, 1, 0, 2, 1, 2, 2, 0, 0, 0, 2, 1, 2, 0]
Test [1, 1, 1, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1, 2, 0]
```

**Comment by lettergram** [comment]
@bharat-patidar wanted to ask if there were still issues?

**Comment by bharat-patidar** [comment]
Hi Austin,
I am using python 3.6 and rest of the configuration is same. Currently my machine is not tied to GPU because I just want to inference with the help of pre-trained model. I was travelling so couldn't check with your updated model file. I will check and will let you know by today.
Thanks for the help. :)

**Comment by bharat-patidar** [comment]
Hi Austin,
I tried with new model file but the error is same. I am running it on my laptop which doesn't have GPU attached. ( No CUDA) Also, I had to upgrade numpy to latest version because it was throwing some errors. Rest all packages have same version mentioned in requirements.txt file.

This is the error when I tried to run latest commit.

`PS C:\Users\Quantiphi\Desktop\bharat\ConvIn\sentence_classification2> python .\sentence_cnn_model_saving.py models/cnn
Using TensorFlow backend.
models/cnn
Load Model? True
Loading Data...
170004 train sequences
42502 test sequences
3 classes
Pad sequences (samples x time)
Convert class vector to binary class matrix (for use with categorical_crossentropy)
Loading model!
WARNING:tensorflow:From C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\tensorflow\p
ython\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be re
moved in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\keras\backen
d\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will
be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-06-12 14:09:43.669083: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that thi
s TensorFlow binary was not compiled to use: AVX2
Loaded model from disk
Traceback (most recent call last):
  File ".\sentence_cnn_model_saving.py", line 137, in <module>
    batch_size=batch_size, verbose=1)
  File "C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\keras\engine\training.py", l
ine 1113, in evaluate
    steps=steps)
  File "C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\keras\engine\training_arrays
.py", line 392, in test_loop
    batch_outs = f(ins_batch)
  File "C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\keras\backend\tensorflow_bac
kend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\keras\backend\tensorflow_bac
kend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\Quantiphi\.virtualenvs\sentence_classification2-4WjXXOjx\lib\site-packages\tensorflow\python\framework\
errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[28,480] = 21478 is not in [0, 15000)
         [[{{node embedding_1/embedding_lookup}}]]`

**Comment by lettergram** [comment]
Unfortunately, I don't know if I can help. 

I've tested this code on OSX, various flavors of Linux with and without a GPU. They all appear to work, this may be an issue with the Windows implementation of tensorflow or something, I cannot rightly say.

**Comment by bharat-patidar** [comment]
Ohkay, No issues Austin.
Thank you so much for your help. I will check and let you know if I get any workaround.

**Comment by bharat-patidar** [comment]
Hi Austin,
Instead of loading pre-trained model I tried to train it from scratch via sentence_cnn_model_saving.py by changing the 'load_model_flag' variable. This time also I got the same error >> InvalidArgumentError: indices[56,450] = 70659 is not in [0, 15000)

So, as I already mentioned this has something to do with input word dimensions (15000) so I changed variable 'max_words' from 15,000 to 150,000 and the **training successfully started**.
I guess pre-trained model might be trained on 15,000 words and default_word_encoding.json file contains more than 1 lac words and that's why model won't be able to find it's indices in pretrained model embeddings. 
What's your thought on this?
This time I did all the experimentation on Ubuntu machine.

**Comment by lettergram** [comment]
Could you provide your `pip freeze`? If a word isnt' in the encoding it should simply drop it. 

It appears that you're program sending a 2D matrix into the model that is supposed to have a 1D vector. I just can't seem to figure out why.

**Comment by bharat-patidar** [comment]
output of pip freeze  >>

`(sentence-classification) ubuntu@ip-172-31-2-227:~/bharat/sentence-classification$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
absl-py==0.7.1
astor==0.8.0
backports.weakref==1.0.post1
beautifulsoup4==4.6.3
enum34==1.1.6
funcsigs==1.0.2
futures==3.2.0
gast==0.2.2
grpcio==1.21.1
h5py==2.8.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
Markdown==3.1.1
mock==3.0.5
nltk==3.4
numpy==1.15.4
protobuf==3.8.0
PyYAML==5.1.1
scipy==1.2.2
singledispatch==3.4.0.3
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
Werkzeug==0.15.4
`

**Comment by lettergram** [comment]
Finally! Managed to recreate the issue, is it possible to use `python 3.5 or higher`? That will solve the issue.

**Comment by bharat-patidar** [comment]
Hi Austin,
I created virtualenv and tried with python 3.5, 3.6 and 3.7. But none of the version worked.
Resulted in the same error. :(

**Comment by lettergram** [comment]
Unfortunately, at this point I have no idea. I cannot replicate the issue exactly.... 

What I will say, is you are using tensorflow (not tensorflow-gpu). I don't suspect that's an issue, but that's what I have as a differentiator.

**Comment by bharat-patidar** [comment]
No issues Austin.
I performed model training from scratch and it worked well. Now I can successfully load my pre-trained model and since model performance is very good with few epochs of training as well, it doesn't make any significant difference to train for a longer time.
Thank you so much for your help. 
This is really helpful!!

**Comment by lettergram** [comment]
I managed to fix it, had to do with a difference with the way embeddings were being handled. Turns out the "max_words" needs to be set to all the encoded words in some cases. I couldn't narrow down why. Anyway, pushed a fix!
