### ISSUE TITLE
Issue with word_embeddings generated from encode_phrases

### ISSUE THREAD

**Issue by acp1997** [lettergram/sentence-classification#4]
While using default **word_encoding** if a word is not present in dictionary key it is given an encoding **0**. I saw your *default_word_encoding.json* and found multiple words have value 0 and so on. If it is intended can I know how model differentiates between new words and seen words with same encoded value?

**Comment by lettergram** [comment]
The current system only has three zero values: 

<img width="437" alt="Screen Shot 2019-06-30 at 2 14 59 PM" src="https://user-images.githubusercontent.com/1498748/60401037-8058e600-9b41-11e9-9fb7-7905c6643f0f.png">

There was actually a bug to-be-honest. In the fork of this we use for [Metacortex](https://metacortex.me/) it's been fixed, but it doesn't really improve performance much...

> If it is intended can I know how model differentiates between new words and seen words with same encoded value?

Regarding your question, the model doesn't differentiate between words it hasn't seen before. It assigns them a zero. If your training data is large and representative enough this should be fine, as we take the top 5-15k words used to create the embeddings. 

This means most (likely the vast majority) of the words when the model is evaluating real samples will map to known encodings. The ones that haven't been seen before are *likely* not adding to the sentence structure enough to make it worth it to keep the encoding. 

It's fairly standard to only keep the mapping of the top XX one-hot encodings. In this case, 10k words seems ample and keeping more hasn't really improved the results.

**Comment by lettergram** [comment]
Should be fixed in latest commit :)
