### ISSUE TITLE
Counts printed by gen_test_comments include duplicates

### ISSUE THREAD

**Issue by saurabhmathur96** [lettergram/sentence-classification#5]
The values being printed by `gen_test_comments` are 
```
-------------------------
command 1672
statement 80993
question 131219
-------------------------
```

However, the actual values are 1111, 80167 and, 131001 for commands, statements and questions respectively. The values stored in the variables like `command_count` include duplicate sentences. 
While the `tagged_comments` dict takes care of duplicate values, the counts still contain duplicates.

**Comment by lettergram** [comment]
Fixed in latest commit :)

Thanks!
